version: 2
jobs:
  build:
    docker:
      - image: ablu/docker-ubuntu-texlive-full
    steps:
      - checkout
      - run:
          command: latexmk main
          working_directory: papers/test1-en
