version: 2

executors:
  my-executor:
    working_directory: /tmp

jobs:
  build:
    docker:
      - image: ablu/ubuntu-texlive-full
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y git ssh
      - checkout
      - run:
          command: |
            cd papers/test1-en
            pwd
            latexmk main
      - persist_to_workspace:
          root: /tmp
          paths:
            - project
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Publish Release on GitHub"
          command: |
            cd /tmp/project/papers/test1-en
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} main.pdf

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
